// Shared data for the spherical gallery (/gallery) and its detail pages.
// Images live in /public/portfolio.

export const galleryProjects = [
  {
    slug: "sham",
    domain: "shamsweets.at",
    title: "Sham Sweets",
    category: "Food & E-Commerce",
    tags: ["FOOD", "E-COMMERCE"],
    year: "2026",
    image: "/portfolio/sham-browser.png",
    headline: "Authentischer Geschmack, online erlebbar gemacht.",
    description:
      "Ein präziser digitaler Auftritt, der Vertrauen, Genuss und Kaufbereitschaft auf den ersten Blick verdichtet.",
    link: "https://shamsweets.at",
  },
  {
    slug: "oasespa",
    domain: "oasespa.at",
    title: "Oase Spa",
    category: "Health & Beauty",
    tags: ["HEALTH", "BEAUTY"],
    year: "2026",
    image: "/portfolio/oasespa-browser.png",
    headline: "Digitale Ruheoase für entspannte Kunden.",
    description:
      "Eine ruhige Premium-Präsenz, die Atmosphäre, Termininteresse und Markenwert souverän zusammenführt.",
    link: "https://oasespa.at",
  },
  {
    slug: "fem",
    domain: "fembeauty.at",
    title: "FEM Beauty",
    category: "Beauty & Wellness",
    tags: ["BEAUTY", "WELLNESS"],
    year: "2026",
    image: "/portfolio/fem-browser.png",
    headline: "Eleganz, die online genauso wirkt wie im Studio.",
    description:
      "Ein fein kuratierter Auftritt, der Ästhetik, Klarheit und gehobenes Vertrauen elegant verbindet.",
    link: "https://fembeauty.at",
  },
  {
    slug: "minicrm",
    domain: "MiniCRM",
    title: "MiniCRM",
    category: "SaaS & Business Tool",
    tags: ["SAAS", "TOOL"],
    year: "2026",
    image: "/portfolio/minicrm-browser.png",
    headline: "Kundenmanagement, einfach und übersichtlich.",
    description:
      "Ein fokussiertes Interface, geschaffen für Übersicht, Geschwindigkeit und professionelle tägliche Nutzung.",
    link: "#",
  },
  {
    slug: "misterm",
    domain: "Mister M",
    title: "Mister M",
    category: "Service & Handwerk",
    tags: ["SERVICE", "HANDWERK"],
    year: "2026",
    image: "/portfolio/misterm-browser.png",
    headline: "Vertrauen schaffen mit klarer Online-Präsenz.",
    description:
      "Eine markante Webpräsenz, die handwerkliche Kompetenz mit hochwertiger digitaler Wirkung übersetzt.",
    link: "https://city-barbershop.simeon-jovicic.workers.dev",
  },
  {
    slug: "choo",
    domain: "choo-foodstore.at",
    title: "Choo Foodstore",
    category: "Food & Retail",
    tags: ["FOOD", "STORE"],
    year: "2026",
    image: "/portfolio/choo-browser.png",
    headline: "Asiatische Vielfalt, digital zum Greifen nah.",
    description:
      "Ein warmer, kuratierter Auftritt, der Sortiment, Standort und Einkaufslust auf einen Blick vermittelt.",
    link: "https://choo-foodstore.at",
  },
  {
    slug: "nes",
    domain: "nes-shop.at",
    title: "NES",
    category: "Fashion & E-Commerce",
    tags: ["FASHION", "E-COMMERCE"],
    year: "2026",
    image: "/portfolio/nes-browser.png",
    headline: "Zurückhaltende Eleganz für eine junge Marke.",
    description:
      "Eine ruhige Premium-Bühne, die Markenwerte, Neugier und Newsletter-Anmeldungen elegant zusammenführt.",
    link: "https://nes-shop.at",
  },
  {
    slug: "datri",
    domain: "datri-shop.at",
    title: "DATRI",
    category: "Sport & E-Commerce",
    tags: ["SPORT", "E-COMMERCE"],
    year: "2026",
    image: "/portfolio/datri-browser.png",
    headline: "Kompromisslose Marke, kompromissloser Auftritt.",
    description:
      "Ein kraftvoller Shop-Auftritt, der Härte, Qualitätsanspruch und klare Kaufwege konsequent verbindet.",
    link: "https://datri-shop.at",
  },
  {
    slug: "kiprofessor",
    domain: "kiprofessor.at",
    title: "KI Professor",
    category: "Education & AI",
    tags: ["KI", "EDUCATION"],
    year: "2026",
    image: "/portfolio/kiprofessor-browser.png",
    headline: "Künstliche Intelligenz, verständlich gemacht.",
    description:
      "Eine klare Lernplattform, die komplexe KI-Themen zugänglich, strukturiert und ansprechend vermittelt.",
    link: "https://kiprofessor.at",
  },
  {
    slug: "lapetitepause",
    domain: "lapetitepause.at",
    title: "La Petite Pause",
    category: "Food & Gastro",
    tags: ["FOOD", "GASTRO"],
    year: "2026",
    image: "/portfolio/lapetitepause-browser.png",
    headline: "Frische Poke Bowls, zweimal täglich frisch gemacht.",
    description:
      "Ein charmanter digitaler Auftritt, der Frische, Sorgfalt und Genuss sympathisch auf den Punkt bringt.",
    link: "#",
  },
  {
    slug: "mhselektro",
    domain: "mhs-elektro.at",
    title: "MHS Elektro",
    category: "Service & Handwerk",
    tags: ["ELEKTRO", "HANDWERK"],
    year: "2026",
    image: "/portfolio/mhselektro-browser.png",
    headline: "Elektroinstallationen, sauber geplant und umgesetzt.",
    description:
      "Eine klare Webpräsenz, die handwerkliche Verlässlichkeit und Erfahrung professionell sichtbar macht.",
    link: "#",
  },
  {
    slug: "atlspeisefett",
    domain: "atl-speisefett.at",
    title: "ATL Speisefett",
    category: "Service & Umwelt",
    tags: ["SERVICE", "UMWELT"],
    year: "2026",
    image: "/portfolio/atlspeisefett-browser.png",
    headline: "Altfett loswerden? Ein Anruf genügt.",
    description:
      "Ein freundlicher Auftritt, der einen Familienbetrieb mit klarem Service modern und vertrauensvoll präsentiert.",
    link: "#",
  },
  {
    slug: "sivar",
    domain: "Sivar",
    title: "Sivar",
    category: "Brand & Web",
    tags: ["BRAND", "WEB"],
    year: "2026",
    image: "/portfolio/laptop-sivar.png",
    fit: "contain", // laptop mockup with transparency — don't crop
    headline: "Ein digitaler Auftritt mit Charakter und Klarheit.",
    description:
      "Eine moderne Markenpräsenz, die Identität, Qualität und Wiedererkennung präzise auf den Punkt bringt.",
    link: "#",
  },
];
